services:
  api:
    container_name: social-api-service
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    expose:
      - ${BACK_PORT}
    networks:
      - internal
    volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
    environment:
      - SERVER_PORT=${BACK_PORT}
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}

  web:
    container_name: social-web
    build:
      context: ./front/web
      dockerfile: Dockerfile.dev
    expose:
      - ${WEB_PORT}
    networks:
      - internal
    volumes:
      - ./front/web:/app:cached
      - front_web_node_modules:/app/node_modules
    environment:
      - PORT=${WEB_PORT}
      # - BACK_URL=${BACK_URL}
    depends_on:
      - api

  proxy:
    container_name: social-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - ${OUT_PORT}:80
    depends_on:
      - api
      - web
    networks:
      - internal

networks:
  internal:

volumes:
  front_web_node_modules:
